### ISSUE TITLE
[BUG] Gas Burst Inconsistency

### ISSUE THREAD

**Issue by Lithrun** [AoTTG-2/AoTTG-2#263] opened 2020-09-05 20:55 UTC
**Describe the bug**
There appears to be inconsistency when gas burst double tap is used, and when the regular gas burst is used. 

**To Reproduce**
1. Host a room
2. Use gas burst without double tap and observe the power and distance you can travel with it
3. Use gas burst with double tap, and compare the two

_Check Controls/Gas Burst Double Tap to enable/disable it_

**Expected behavior**
It is expected that gas burst works identical whether a player double taps or without a double tap.

**Screenshots**
https://youtu.be/pSExVmozaYo

**Additional context**
This was reported in Unity 2017, but issue should still be present in Unity 2020.

**Comment by SlowDeepExhalation** [comment] 2020-10-27 17:02
The bug seems to be that **the doubletap burst animation is automatically being interrupted if used during an aerial dodge**.

It appears to work identically to burst interrupts, used in high level play: gas bursts cause your character to to instantly gain a great deal of acceleration, and then to go through an animation which decelerates them by an equivalent amount over its duration.  Interrupting the animation early (by landing a hook, or sliding on the ground, for instance) causes the burst animation to stop, and therefore prevents it from applying the deceleration effect.  The burst animation *also* causes you to be unable to gas throughout its duration; interrupting it early lets you resume gassing.

In this case, it appears that the burst animation is either being interrupted **immediately** after the initial boost in acceleration, or it's never actually being started.  Also, the bug seems to only occur if you use a doubletap burst during a dodge animation.  Otherwise, bursts seem to work identically between rebind and doubletap--though I have not tested this exhaustively.

**Comment by Acros5542** [comment] 2021-04-12 11:17
To describe this issue better, in AoTTG1, there are currently two types of gas burst.
Double-Tap gas burst and Rebound gas burst.

Despite one being a rebind for the default controls, due to a bug present in RC and other mods, they function differently. However, this is not a bug that should be fixed thoughtlessly. Rebound gas burst behaves differently than double-tap, and thus has a different set of uses. Notably, cancelling a double-tap gas burst will always offer the same increase in speed, but cancelling a rebound gas burst can offer 2x or even 3x your normal increase in speed at the cost of more gas and being much harder and finicky to perform.

Fixing this difference could be done in a few ways, but which decision made needs to be a deliberate one with community feedback. You could simply make both forms of gas burst identical to double-tap, although this will upset some players, notably some racing community members. You could leave it as is in AoTTG1, although this too will upset some players, as mods such as Anarchy have fixed the rebound gas burst to act as double-tap. You could take the approach Anarchy mod later adopted, which was to add an option for rebound gas burst to act in its "legacy" form or behave as double-tap gas burst does. Or you could even make two entire separate bindings for the two separate gas bursts and later players set it however they want to.

These are the kinds of niche factors that show up when developing a game like AoTTG2 that can have a significant impact on the final product, and none of them should ever be made without feedback from the community. I would advise waiting until later in development when the rest of the game behaves closer to AoTTG1 and allowing the players who would be most affected by this change to provide direct input on the matter.

**Closed as completed** 2021-10-30 12:21 UTC
Labels: Bug, Development Team, Investigate, Alpha 3
