### ISSUE TITLE
[BUG]titan amputation bugs

### ISSUE THREAD

**Issue by Hentai-Gentleman** [AoTTG-2/AoTTG-2#127] opened 2020-05-11 18:46 UTC
**Bug**: amputating both legs of a titan won't make it fall, you need to cut an arm to in order for it to fall. once the titan falls, it will never recover

**How to reproduce**:
- cut a titan's legs and it will keep walking
- cut an arm too and it will finally fall
- the titan will never recover from the grounded state, even after its limbs completely grow back

**Expected behavior**: the titan should fall once both legs are cut, also the titan should recover from the grounded animation after its legs grow back

**Additional context** a recording of the bug in action https://youtu.be/n02EuHGVtSg

**Comment by KoroSensei0320** [comment] 2020-05-11 23:17
From a Mac user
Although this can happen, it isn't happening too often for me (perhaps 1/5th of the time).
Furthermore, most titans in a grounded state **will** recover once the legs/leg grow back.

**Comment by Lithrun** [comment] 2020-05-12 10:51
Appeared to be related to the titan recovery state (when they run low on stamina). Should be resolved in d6e0c227e872ba68a43291ee9d188515285dc6bb

**Comment by desu7** [comment] 2020-05-13 13:37
Related to this bug, I did a video where I show another ways you can trigger the bug.
https://www.youtube.com/watch?v=o__BpacxJyo
Along with the output log of the same video https://pastebin.com/nhhyaRf2

Note: This was BEFORE Issue 126 & 127 update, in other words, I would need to check if the bug has been fixed if you trigger it this way.

**Comment by SlowDeepExhalation** [comment] 2020-05-13 18:59
Various amputation issues have been reproduced  in build "Issue126&127".  Testers haven't yet figured out the exact situations in which it happens, but are making good progress on it.

**Comment by Lithrun** [comment] 2020-05-13 20:35
> 
> 
> Related to this bug, I did a video where I show another ways you can trigger the bug.
> https://www.youtube.com/watch?v=o__BpacxJyo
> Along with the output log of the same video https://pastebin.com/nhhyaRf2
> 
> Note: This was BEFORE Issue 126 & 127 update, in other words, I would need to check if the bug has been fixed if you trigger it this way.

@desu7 Confirm that this has been fixed in Build126&127



> 
> 
> Various amputation issues have been reproduced in build "Issue126&127". Testers haven't yet figured out the exact situations in which it happens, but are making good progress on it.

@SlowDeepExhalation be more precise, as what are "various issues"? If there's additional issues related to amputation, then report them.

**Comment by SlowDeepExhalation** [comment] 2020-05-14 14:32
Titans can still walk around with amputated legs in some cases.  Multiple legs being cut seems to be related.  Cutting legs after a titan has been downed once and gotten back up seems to cause it.
Titans do not always get up after being knocked down.  Currently the best theory for why this happens is cutting off an arm that a titan attacked with, then cut the other arm, then cutting both legs in the same order.  This does not seem to be the only way, as titans have stayed down after only leg amputations, occasionally, but no consistent method has been found.
Amputated legs can still be used for kick attacks (and are lethal) but it has been pointed out that this isn't necessarily a bug; titans with amputated legs should be downed and therefore not have the option to attack at all.

All of these are tester theories and are not necessarily duplicable.  As I said, amputations are being actively tested to figure out exact details.  More is found out every day.

**Comment by Lithrun** [comment] 2020-05-15 07:11
> 
> 
> Titans can still walk around with amputated legs in some cases. Multiple legs being cut seems to be related. Cutting legs after a titan has been downed once and gotten back up seems to cause it.
> Titans do not always get up after being knocked down. Currently the best theory for why this happens is cutting off an arm that a titan attacked with, then cut the other arm, then cutting both legs in the same order. This does not seem to be the only way, as titans have stayed down after only leg amputations, occasionally, but no consistent method has been found.

This was related to titans turning while getting their knees sliced.
I also noticed another issue where titans could get up if they had regrown one leg again instead of two.

Both of these are resolved as per 0a4fd606cf8773ca733b406d13c50bcf7c78d2ca

>Amputated legs can still be used for kick attacks (and are lethal) but it has been pointed out that this isn't necessarily a bug; titans with amputated legs should be downed and therefore not have the option to attack at all.
Cannot seem to reproduce this, might be solved due to above.

**Comment by Lithrun** [comment] 2020-05-29 01:57
Included in #170

**Closed as completed by Lithrun** 2020-05-29 01:57 UTC
Labels: Bug, Development Team, Confirmed on Mac, Confirmed on PC
