### ISSUE TITLE
[BUG] You're able to spawn as a Player Titan on any map

### ISSUE THREAD

**Issue by Acros5542** [AoTTG-2/AoTTG-2#502] opened 2021-01-31 01:31 UTC
**Describe the bug**
Currently there is no limitation to what maps you are allowed to spawn as a player titan on. Less of a bug than something worth fixing before release since it doesn't make sense on certain maps such as Racing Akina, and can even be problematic on maps meant for Human vs Human PvP such as Cave Fight or House Fight.

**To Reproduce**
1. Go to any map
2. Press 1
3. Try to spawn as a Titan

**Expected behavior**
Playing as a Player Titan should only be available on certain maps.

**Screenshots**
![Screenshot (515)](https://user-images.githubusercontent.com/75679898/106372084-11a1c700-633a-11eb-941a-22a54f9a04ec.png)

**Contributor instructions**
1. Try to recreate the bug via the reported reproduction steps. If the bug can be reproduced, remove the investigation label. If the bug cannot be reproduced, please add a comment, attach "On Hold" label and inform the submitter that the bug cannot be reproduced. If there is no reply after 2 weeks, the issue can be closed.
2. Follow the default development team procedures (Create a new branch, apply your fix, create a pull request, submit new builds for testing team in dev squad)
3. Once testing team has confirmed the issue is resolved and the pull request is accepted, the issue can be closed.

**Comment by Lithrun** [comment] 2021-02-03 17:35
Duplicate of #508. Closing this one and adding Akina as an extra exclusion.

**Closed as completed by Lithrun** 2021-02-03 17:35 UTC
Labels: Bug, Development Team, Investigate

**Comment by Acros5542** [comment] 2021-02-05 04:11
Technically I reported these separately as this was the issue for being able to spawn as a Titan on any map, and #508 was just pertaining to the error message given when spawning as a Titan on a map that didn't have the room/proper spawn regions for it. But since there's no other places besides House Fight that has this problem currently, it's not a big deal to just make #508 the issue for being able to spawn as a Titan on any map and keeping this one closed.
